services:
  mongo:
    image: mongo
    container_name: mongo-container
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data

  postgres:
      image: postgres
      container_name: postgres-container
      ports:
        - "5433:5432"
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: inventory_db
      volumes:
        - postgres-data:/var/lib/postgresql/data

volumes:
  mongo-data:
  redis-data:
  postgres-data: