import type React from "react"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import ClientLayout from "./ClientLayout"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
    generator: 'v0.dev'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
  <ClientLayout>
    <RequireAuth>
      {children}
    </RequireAuth>
  </ClientLayout>
)
}


import './globals.css'
import RequireAuth from "@/components/RequireAuth"
