services:
  elasticsearch:
    image: elastic/elasticsearch:8.17.5
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Desactiva seguridad para desarrollo
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  kibana:
    image: elastic/kibana:8.17.5
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

  logstash:
    image: elastic/logstash:8.17.5
    volumes:
      - ./logstash-config:/usr/share/logstash/pipeline/
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch

volumes:
  es_data: